### ISSUE TITLE
Can't plot in polar projections

### ISSUE THREAD

**Issue by koldunovn** [ajheaps/cfplot#1]
Dear Andrew,

first of all many thanks for this nice module!

I am trying to use it in IPython notebook, and experience problems with plotting polar projections. It seems like proj='npstere' in `mapset` does not have any effect...

Here is an example (I use NCEP reanalysis data)
http://nbviewer.ipython.org/gist/koldunovn/6eeaaf5b4741fefc14f1

**Comment by ajheaps** [comment]
Dear koldunovn,

I'm really sorry I haven't replied earlier - I've just seen your issue as it's the first one.  

I've just tested your code with the latest cfplot (1.7.3) and it looks fine and produces a polar plot as expected.  Could you try again with the new cfplot and let me know how you get on?

Regards
Andy
